### ISSUE TITLE
RPM package in Fedora - problem with Typer version

### ISSUE THREAD

**Issue by frenzymadness** [datarootsio/databooks#46]
Hi!

I really enjoyed your talk on PyCon PL today and I've decided that it'd be great to have databook packaged in Fedora Linux. I've tried to create a package but found a problem - we have too new type in Fedora (version 0.6.1) but databook requires version < 0.5.

https://github.com/datarootsio/databooks/blob/0b1d3e67c5fd00a145179545a456786bab5b7e77/pyproject.toml#L20

Would it make sense to make the requirement less strict? If thy are following semantic versioning, something like <1.0.0 should guarantee enough stability.

**Comment by frenzymadness** [comment]
I'm trying to create an RPM package for databook which means it has to depend on system Python packages. This is not really a problem because I can relax the version limitation before I install all dependencies.

If you want, the `>=0.4,<1.0.0` can be specified as `^0.4` (without the last zero.

**Comment by murilo-cunha** [comment]
Ahhhhh that makes a lot more sense!
Thanks for the clarification! I had the impression I was missing something (and was right 😁)

I don't think ^0.4 will work for poetry 

> does not modify the left-most non-zero digit in the major, minor, patch grouping

So the minor for us.. but I wouldn't mind being more explicit here

https://python-poetry.org/docs/dependency-specification/#caret-requirements

**Comment by murilo-cunha** [comment]
And thanks for the contribution!!! I really appreciate it 🚀🚀🚀
