### ISSUE TITLE
pytest 7.2.0 no longer depends on py

### ISSUE THREAD

**Issue by frenzymadness** [datarootsio/databooks#47]
This will no longer work with pytest 7.2.0 and higher. `py` lib is deprecated but you can fix the problem by requiring it explicitly if there is no other way now.

https://github.com/datarootsio/databooks/blob/6febdbadde115cdb6fb89eec737d00cfff1d3223/tests/test_common.py#L3

**Comment by murilo-cunha** [comment]
Yes and there's a security update as well from dependabot for `py`

It's definitely on my TODO list. Ooooooor, if you'd like to contribute I'd bee more than happy 😇 

https://github.com/datarootsio/databooks/security/dependabot/2

**Comment by murilo-cunha** [comment]
Closed by https://github.com/datarootsio/databooks/pull/51

Thanks again for the contribution!! ❤️
