### ISSUE TITLE
Can I have the pre-commit hook recurse subdirectories?

### ISSUE THREAD

**Issue by tonyreina** [datarootsio/databooks#49]
I'd like to use databooks in the pre-commit Git hook, but my notebooks are in a sub-folder called "notebooks". Is there a way to specify that in the pre-commit?

**Comment by murilo-cunha** [comment]
This is more of a `pre-commit` question, but I'll post my thoughts here:

Yes. You can specify which files each hook should run with the `files:` argument. You can specify this globally as well for all hooks.

But, by default, the `databooks-assert` and `databooks-meta` hooks will only run on notebooks (ie.: `.ipynb` files). So it'd only make sense to specify this if you also have notebooks in other directories that you don't want to run this hooks 🙂 

Hope this helps! 🚀
