### ISSUE TITLE
move to pydantic v2

### ISSUE THREAD

**Issue by murilo-cunha** [datarootsio/databooks#65]

**Comment by astronautas** [comment]
I'll grab this

**Comment by astronautas** [comment]
Managed to migrate as far as to Pydantic v2.1.*. To minimize the blast radius of changes, stopped there. Will raise a PR.

**Comment by astronautas** [comment]
Managed to bump pydantic to v2.2.*. To keep the scope of PR within reasonable bounds, not bumping for more, for now (since v2.3.* requires even more changes).
